image: registry.gitlab.com/gitlab-org/gitlab-runner/dind:latest

variables:
  GIT_STRATEGY: clone
  PAGES_PATH: public # This is the default path GitLab Pages looks for

stages:
  - build
  - deploy

build_documentation:
  stage: build
  script:
    - apt-get update && apt-get install -y doxygen graphviz # Install Doxygen and Graphviz
    - mkdir -p docs
    - cd docs
    - doxygen ../Doxyfile # Assuming your Doxyfile is in the root of the repository
    - mv html ../$PAGES_PATH # Move the generated HTML documentation to the public directory
  artifacts:
    paths:
      - $PAGES_PATH

pages:
  stage: deploy
  needs: [build_documentation]
  script:
    - echo "Deploying documentation to GitLab Pages..."
  artifacts:
    paths:
      - $PAGES_PATH
